<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <groupId>com.github.cabutchei.wtpcomponent</groupId>
  <artifactId>com.github.cabutchei.wtpcomponent.parent</artifactId>
  <version>0.1.0-SNAPSHOT</version>
  <packaging>pom</packaging>

  <properties>
    <tycho.version>4.0.4</tycho.version>
    <maven.compiler.release>17</maven.compiler.release>
  </properties>

  <modules>
    <module>com.github.cabutchei.wtpcomponent.lsp.app</module>
    <module>com.github.cabutchei.wtpcomponent.lsp.feature</module>
    <module>com.github.cabutchei.wtpcomponent.lsp.product</module>
  </modules>

  <build>
    <plugins>
      <plugin>
        <groupId>org.eclipse.tycho</groupId>
        <artifactId>tycho-maven-plugin</artifactId>
        <version>${tycho.version}</version>
        <extensions>true</extensions>
      </plugin>
      <plugin>
        <groupId>org.eclipse.tycho</groupId>
        <artifactId>tycho-compiler-plugin</artifactId>
        <version>${tycho.version}</version>
        <configuration>
          <source>17</source>
          <target>17</target>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.eclipse.tycho</groupId>
        <artifactId>target-platform-configuration</artifactId>
        <version>${tycho.version}</version>
        <configuration>
          <pomDependencies>consider</pomDependencies>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <repositories>
    <repository>
      <id>eclipse-2024-09</id>
      <layout>p2</layout>
      <url>https://download.eclipse.org/releases/2024-09</url>
    </repository>
    <repository>
      <id>eclipse-orbit-R20240531</id>
      <layout>p2</layout>
      <url>https://download.eclipse.org/tools/orbit/downloads/drops/R20230531010532/repository</url>
    </repository>
    <repository>
      <id>eclipse-orbit-R20180606</id>
      <layout>p2</layout>
      <url>https://download.eclipse.org/tools/orbit/downloads/drops/R20180606145124/repository</url>
    </repository>
  </repositories>
</project>
